//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.08 at 11:01:03 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://thomas-bayer.com/blz/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.task1.demo.wsdlStub;
